### ISSUE TITLE
Georgia Jones converted to opportunity and lost previous activities

### ISSUE THREAD

**Issue by saf28** [MelHarbour/cuwbc-crm#319]
Converted her from a lead and the previous activities are no longer listed... is this something to do with Lead -> Opportunity?

**Comment by MelHarbour** [comment]
I suspect that it hasn't copied the activities across. They'll still be there, just attached to the wrong entity.

**Comment by saf28** [comment]
This happens to everyone that is converted from Lead to opportunity... really need to get this sorted - tagging as high priority.
