### ISSUE TITLE
Upcoming activities

### ISSUE THREAD

**Issue by saf28** [MelHarbour/cuwbc-crm#324]
These are all showing as though they're past date (shaded) whether they are or not! It used to just show them as shaded if they were overdue.

**Comment by MelHarbour** [comment]
Problem is server side - the 'complete' flag is coming through as false even when it should be true. Need to look in the Activities API controller.

**Comment by saf28** [comment]
It's done it the wrong way round - ones that are upcoming are still shaded, but the one that's passed is now normal looking! Sorry!
