### ISSUE TITLE
Listing grad / under grad applicants

### ISSUE THREAD

**Issue by saf28** [MelHarbour/cuwbc-crm#393]
Currently it lists them as grad/undergrad based on the course picked. THis is a bit crude, and we probably need to include a separate box to show whether they're a school leaver or already at university etc... also we need to know whether they're going to be undergrad (i.e. currently at school) even before we've actually got a course picked for them...

**Comment by MelHarbour** [comment]
Needs to be a property of the Opportunity/Lead (needs to be on both).

People applying for mature/affiliated should still be 'grad'.

**Comment by MelHarbour** [comment]
On the Opportunities Index page, pull through the level with the following order of precedence:

1. Profile
2. Application(s) - as we have at the moment
