### ISSUE TITLE
Adding a contact to a department/college etc

### ISSUE THREAD

**Issue by saf28** [MelHarbour/cuwbc-crm#413]
Just tried to Add Simon Learmount to the JBS and it didn't give me the option of adding people from the list of contacts already listed in the system. Was just a free-form box, which when I then typed his name in and pressed submit, I got a pop up in the bottom left corner to say 'there was a problem submitting the request' - suspect this is the same issue Siobhan had - but I've still not had anything from her to say what it was...

**Comment by MelHarbour** [comment]
I think this is working now.
