### ISSUE TITLE
Need a new category of lost/extinct

### ISSUE THREAD

**Issue by saf28** [MelHarbour/cuwbc-crm#425]
May have someone who gets on a course and comes to Cambridge, but who decides not to row for CUWBC... not sure whether this needs to go in the course section or the extinct section?

**Comment by MelHarbour** [comment]
This is actually already somewhat captured in #160

**Comment by MelHarbour** [comment]
I don't think extinct is necessarily the way to go on these - it feels like a sub-class of 'won' for an application. As in we've successfully got them into the Uni on that application, but then something else has gone wrong.

Eventually, it would probably be about whether or not they're converted into 'athlete' or similar, but for the time being, we'll add another application status in.
