### ISSUE TITLE
Box size for entering text for an activity is minute

### ISSUE THREAD

**Issue by saf28** [MelHarbour/cuwbc-crm#431]
Can't properly see what it is that I'm adding - any chance of having that expanded to be a similar size to what it was before?

**Comment by saf28** [comment]
Ok box fixed now... but Date is a bit weird still! When you enter the date it's actually obscured by the word 'Date' in the top left; also it pops out and displays January 2015 as the first option.

**Comment by MelHarbour** [comment]
The date label will now display better. Can't do anything about the Jan 15 option default at the moment.
