### ISSUE TITLE
Filter on years isn't working

### ISSUE THREAD

**Issue by saf28** [MelHarbour/cuwbc-crm#435]
On the oportunity page - can now see the year filters at the top but clicking on the menus isn't filtering it out

**Comment by saf28** [comment]
ok weird - so it works in leads, and if you set it in leads and then go to opportunities its then got the same filter applied...

**Comment by MelHarbour** [comment]
Discovered I'd actually already fixed it in leads - I knew the filter is the same across both categories. Fix incoming.
