### ISSUE TITLE
Create opportunity not working

### ISSUE THREAD

**Issue by saf28** [MelHarbour/cuwbc-crm#448]
Just tried to create Emma Twigg... and when I hit submit, the form goes blank. I searched for her to double check that it hadn't been created anyway, and it hadn't!

**Comment by MelHarbour** [comment]
Looks like it's not liking a blank date of birth.

**Comment by saf28** [comment]
hmm - but if I don't have her DoB?

**Comment by MelHarbour** [comment]
Sorry - was more a comment to myself on what the problem was. I'm fixing it now!
