### ISSUE TITLE
Linking through between applicants and contacts

### ISSUE THREAD

**Issue by saf28** [MelHarbour/cuwbc-crm#451]
Quite often I query courses or stuff with contacts, and I'm not actually sure whether to put the comment in the contacts profile or in the applicant's profile! I guess it would be good to have an alternative activity called something like 'query' where you can then select the contact that you're asking, and it'll then duplicate the information into their profile, but also show up in the applicant's profile so that progress can be tracked?

**Comment by MelHarbour** [comment]
This is actually #186
