### ISSUE TITLE
Option for pooled candidates that are won

### ISSUE THREAD

**Issue by saf28** [MelHarbour/cuwbc-crm#93]
College applied to won't be the same as college they end up in... need some way of tracking what the pool college is - also would be useful to include that for those who are pooled to a college and rejected...

**Comment by saf28** [comment]
Need to do something to be able to track if people are lost at the pool stage - so would it be possible to add in a 'reason for being lost' e.g.
rejected at interview
pooled and not re-interviewed
pooled and re-interviewed then rejected
Didn't make offer

**Comment by saf28** [comment]
Ideally would like to get this added soonish before I forget what happened to people!

**Comment by MelHarbour** [comment]
Do you want to add these statuses into the normal set of status? We currently have a 'pooled, rejected' reason for being lost and we can easily add a load more reasons into that to cover more scenarios. That would be quick and easy to do. For clarity, the complete list of reasons we currently have available is:

* Did not apply
* Rejected before interview
* Rejected after interview
* Pooled, rejected
* Missed grades
* Did not accept offer

**Comment by MelHarbour** [comment]
Just need to add in 'pooled and not re-interviewed' and 'pooled, reinterviewed, rejected' as statuses, and add pooledcollege as an extra piece of data on an application.

**Comment by MelHarbour** [comment]
Also could do with adding summer pool college.
